### ISSUE TITLE
Read

### ISSUE THREAD

**Issue by ProgrammierZero** [Cynderblood/minimalist-rpg#1]
Hey! I have my version of text rpg. If you want, we can continue my version or start working with yours.
See this in my repositories, and answer.

**Comment by Cynderblood** [comment]
I'll happily help with bugs that I am capable of fixing in your RPG. Keep in mind that I am relatively new to Python, so I'll keep my main focus on my project. Let me know if you need any help, I've put your repository on my watchlist.

**Comment by ProgrammierZero** [comment]
Good, so i'll help you with your project, i think when we work together we getting more experience. So tomorrow we can start working on your project :)
