### ISSUE TITLE
Upload doesn't work

### ISSUE THREAD

**Issue by ProgrammierZero** [Cynderblood/minimalist-rpg#3]
![Problem](https://user-images.githubusercontent.com/57979201/85172343-89265880-b279-11ea-9fcf-a448ed35b964.png)

**Comment by ProgrammierZero** [comment]
i think, you need to add me in contributors.

**Comment by ProgrammierZero** [comment]
And write please your time now, because i can't contact you by my time, maybe you have a night when i have a day

**Comment by ProgrammierZero** [comment]
i don't answer, i'll answer tommorow.

**Comment by Cynderblood** [comment]
https://github.com/Cynderblood/minimalist-rpg/invitations Sorry, but I'm very new to github.

**Comment by ProgrammierZero** [comment]
Don't mind, i'm too.
